"""add favorites notifications and indexes

Revision ID: 3f398c77bdb4
Revises: 281d70ea00eb
Create Date: 2026-04-12 01:46:50.929715

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f398c77bdb4'
down_revision = '281d70ea00eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('favorite_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['favorite_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'favorite_user_id', name='uq_favorite_pair')
    )
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_favorites_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_favorite_user_id'), ['favorite_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_favorites_user_id'), ['user_id'], unique=False)

    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('related_user_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['related_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notifications_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_is_read'), ['is_read'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_related_user_id'), ['related_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_notifications_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_likes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_from_user_id'), ['from_user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_likes_to_user_id'), ['to_user_id'], unique=False)
        batch_op.create_unique_constraint('uq_like_pair', ['from_user_id', 'to_user_id'])

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matches_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user1_id'), ['user1_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matches_user2_id'), ['user2_id'], unique=False)
        batch_op.create_unique_constraint('uq_match_pair', ['user1_id', 'user2_id'])

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_receiver_id'), ['receiver_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_messages_sender_id'), ['sender_id'], unique=False)

    with op.batch_alter_table('profile_photos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_profile_photos_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_photos_is_primary'), ['is_primary'], unique=False)
        batch_op.create_index(batch_op.f('ix_profile_photos_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profiles_user_id_key'), type_='unique')
        batch_op.create_index(batch_op.f('ix_profiles_display_name'), ['display_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_gender'), ['gender'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_looking_for'), ['looking_for'], unique=False)
        batch_op.create_index(batch_op.f('ix_profiles_user_id'), ['user_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_profiles_visibility'), ['visibility'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profiles_visibility'))
        batch_op.drop_index(batch_op.f('ix_profiles_user_id'))
        batch_op.drop_index(batch_op.f('ix_profiles_looking_for'))
        batch_op.drop_index(batch_op.f('ix_profiles_gender'))
        batch_op.drop_index(batch_op.f('ix_profiles_display_name'))
        batch_op.create_unique_constraint(batch_op.f('profiles_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profile_photos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_profile_photos_user_id'))
        batch_op.drop_index(batch_op.f('ix_profile_photos_is_primary'))
        batch_op.drop_index(batch_op.f('ix_profile_photos_created_at'))

    with op.batch_alter_table('messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_messages_sender_id'))
        batch_op.drop_index(batch_op.f('ix_messages_receiver_id'))
        batch_op.drop_index(batch_op.f('ix_messages_created_at'))

    with op.batch_alter_table('matches', schema=None) as batch_op:
        batch_op.drop_constraint('uq_match_pair', type_='unique')
        batch_op.drop_index(batch_op.f('ix_matches_user2_id'))
        batch_op.drop_index(batch_op.f('ix_matches_user1_id'))
        batch_op.drop_index(batch_op.f('ix_matches_created_at'))

    with op.batch_alter_table('likes', schema=None) as batch_op:
        batch_op.drop_constraint('uq_like_pair', type_='unique')
        batch_op.drop_index(batch_op.f('ix_likes_to_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_status'))
        batch_op.drop_index(batch_op.f('ix_likes_from_user_id'))
        batch_op.drop_index(batch_op.f('ix_likes_created_at'))

    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notifications_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_type'))
        batch_op.drop_index(batch_op.f('ix_notifications_related_user_id'))
        batch_op.drop_index(batch_op.f('ix_notifications_is_read'))
        batch_op.drop_index(batch_op.f('ix_notifications_created_at'))

    op.drop_table('notifications')
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_favorites_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_favorite_user_id'))
        batch_op.drop_index(batch_op.f('ix_favorites_created_at'))

    op.drop_table('favorites')
    # ### end Alembic commands ###
